version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: overthewire-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overthewire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: overthewire-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: overthewire-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres


volumes:
  pgdata:
